apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.oracle.com
  labels:
    release: release-name
    chart: mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  scope: Cluster
  names:
    kind: Cluster
    singular: cluster
    plural: mysqlclusters
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.oracle.com
  labels:
    release: release-name
    chart: mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  scope: Cluster
  names:
    kind: Backup
    singular: mysqlbackup
    plural: mysqlbackups
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlrestores.mysql.oracle.com
  labels:
    release: release-name
    chart: mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  scope: Cluster
  names:
    kind: Restore
    singular: mysqlrestore
    plural: mysqlrestores
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupschedules.mysql.oracle.com
  labels:
    release: release-name
    chart: mysql-operator-0.2.1
spec:
  group: mysql.oracle.com
  scope: Cluster
  names:
    kind: BackupSchedule
    singular: mysqlbackupschedule
    plural: mysqlbackupschedules
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
