apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - update
      - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
      - mysqlbackups
      - mysqlbackupschedules
      - mysqlclusters
      - mysqlclusters/finalizers
      - mysqlrestores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
